### ISSUE TITLE
bin dist type with no output panics

### ISSUE THREAD

**Issue by gdearment** [palantir/distgo#112]
I'm trying to run a manual `dist` task without a `build` task for a product and it panics:
config:
```
products:
  project:
    dist:
      disters:
        type: manual
        config:
          extension: tgz
        script: |
          #!/usr/bin/env bash
          echo "hi"
```
generates this:
```
➜  project git:(gd/initial2) ✗ ./godelw dist planer
Creating distribution for planer at out/dist/planer/unspecified/bin/project-unspecified.tgz
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13f9aaa]

goroutine 1 [running]:
github.com/palantir/distgo/dister/bin.(*Dister).RunDist(0x1975888, 0xc42002b607, 0x3, 0x7ffeefbff4fd, 0x3d, 0x160719f, 0xb, 0xc42002b640, 0x6, 0x0, ...)
	/go/src/github.com/palantir/distgo/dister/bin/dister.go:52 +0x3a
github.com/palantir/distgo/distgo/dist.Run(0x7ffeefbff4fd, 0x3d, 0x160719f, 0xb, 0xc42002b640, 0x6, 0x0, 0x0, 0xc420182b20, 0x0, ...)
	/go/src/github.com/palantir/distgo/distgo/dist/dist.go:160 +0x73b
github.com/palantir/distgo/distgo/dist.Products(0x7ffeefbff4fd, 0x3d, 0x160719f, 0xb, 0xc42015d420, 0x0, 0x0, 0x1672fe0, 0x1975888, 0x1671940, ...)
	/go/src/github.com/palantir/distgo/distgo/dist/dist.go:107 +0xc6d
github.com/palantir/distgo/cmd.glob..func6(0x1950700, 0xc42013f340, 0x1, 0x7, 0x0, 0x0)
	/go/src/github.com/palantir/distgo/cmd/dist.go:41 +0x250
github.com/palantir/distgo/vendor/github.com/spf13/cobra.(*Command).execute(0x1950700, 0xc42012e240, 0x7, 0xc, 0x1950700, 0xc42012e240)
	/go/src/github.com/palantir/distgo/vendor/github.com/spf13/cobra/command.go:756 +0x468
github.com/palantir/distgo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1951a00, 0xc42008df80, 0x1604def, 0x5)
	/go/src/github.com/palantir/distgo/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/palantir/distgo/vendor/github.com/palantir/pkg/cobracli.Execute(0x1951a00, 0xc42008df50, 0x3, 0x3, 0x0)
	/go/src/github.com/palantir/distgo/vendor/github.com/palantir/pkg/cobracli/execute.go:30 +0xea
github.com/palantir/distgo/vendor/github.com/palantir/pkg/cobracli.ExecuteWithDebugVarAndDefaultParams(0x1951a00, 0x1975630, 0x0, 0x0, 0x0, 0xc420059f78)
	/go/src/github.com/palantir/distgo/vendor/github.com/palantir/pkg/cobracli/default.go:36 +0x10d
github.com/palantir/distgo/cmd.Execute(0xc42001c0a0)
	/go/src/github.com/palantir/distgo/cmd/root.go:60 +0x4a
main.main()
	/go/src/github.com/palantir/distgo/main.go:34 +0xe6
```

**Comment by nmiyake** [comment]
Will take a closer look, but I think there's something wrong with the configuration -- based on the panic trace, it's trying to execute the `bin` dister rather than the `manual` dister

**Comment by nmiyake** [comment]
Hmm what version are you using? I created a new project, used the exact config in the issue and ran `./godelw dist` and it runs:

```
➜  test-dist ./godelw dist
Creating distribution for project at out/dist/project/unspecified/manual/project-unspecified.tgz
hi
Error: dist failed for project: expected output does not exist at /Volumes/git/go/src/github.com/nmiyake/test-dist/out/dist/project/unspecified/manual/project-unspecified.tgz: stat /Volumes/git/go/src/github.com/nmiyake/test-dist/out/dist/project/unspecified/manual/project-unspecified.tgz: no such file or directory
```

**Comment by gdearment** [comment]
Running 2.8.0

**Comment by nmiyake** [comment]
Is that config edited or literal? In the pasted config, the project is named `project`, but your command is `./godelw dist planer` -- is `planer` defined somewhere else in `dist.yml`? If you're using exactly the config you pasted, the command should be `./godelw dist project`.

Yeah 2.8.0 is what I'm using as well -- pushed example repo that works with exact config you pasted at https://github.com/nmiyake/godel-manual-dist-example.

**Comment by nmiyake** [comment]
Discussed offline, and the actual configuration is:

```yaml
product-defaults:
  build:
    environment:
      CGO_ENABLED: "0"
    os-archs:
    - os: linux
      arch: amd64
  dist:
    disters:
      bin:
        type: bin
  publish:
    group-id: project-id
products:
  project:
    dist:
      disters:
        type: manual
        config:
          extension: tgz
        script: |
          #!/usr/bin/env bash
          echo "Hello"
# other products
```

The actual issue is that the `bin` dister is failing with a panic when there is no output (the product has a `bin` dister and `manual` dister due to config inheritance merging maps).
