### ISSUE TITLE
Add `build-args-script` option to add flexibility to docker build arguments

### ISSUE THREAD

**Issue by jamesross3** [palantir/distgo#119]
One simple use case: I'd like to specify my base image version in only one place, but I have multiple `Dockerfile`s referenced in my `distgo` configuration. Given a file `base-image.version` with the contents `1.0.0`, I'd like to be able to have my docker command look something like:
`docker build --build-args BASE_IMAGE_VERSION=1.0.0`. A valid approach could look like:

```
products:
  foo:
    # build and dist blocks
    docker:
      docker-builders:
            build-1:
              # other fields...
              config:
                  build-args-script: |
                    echo "--build-args BASE_IMAGE_VERSION=$(cat base-image.version)"
```
@nmiyake
