### ISSUE TITLE
Dist filtering improperly filters dependent product dist tasks

### ISSUE THREAD

**Issue by nmiyake** [palantir/distgo#77]
Define a product with the following structure:

```yaml
products:
  test-1:
    dist:
      disters:
        dister-1-1:
          # definition
        dister-1-2:
          # definition
    dependencies:
      - test-2
  test-2:
    dist:
      disters:
        dister-2-1:
          # definition
        dister-2-2:
          # definition
```

Run `./godelw dist test-1.dister-1-1 test-2.dister-2-1`

Expected
---------
`test-1.dister-1-1`, `test-2.dister-2-1` and `test-2.dister-2-2` should all be run

Actual
------
Only `test-1.dister-1-1` and `test-2.dister-2-1` are run

Fix
---
This is an issue with over-eager filtering. The fix is to implement an algorithm like the following:

* Determine all the dist IDs specified
* For each of the specified dist IDs, look up the product and get all of its dependent products
  * Add the productID of each of those dependent products as a specified dist ID
* Perform filtering logic currently used
